# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9370e3eb10cfb695fefd54f90a15b8e9"
application_url = "https://new.magento-development.asia/like-app/install.php"
embedded = true
name = "WTS review"
handle = "wts-review"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[auth]
redirect_urls = [
  "https://new.magento-development.asia/like-app/generate_token.php",
  "https://new.magento-development.asia/like-app/app/Views/home.php"
]

[pos]
embedded = true
